version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: opus
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./:/app
      - media:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python -m worker.run_worker
    env_file: .env
    volumes:
      - ./:/app
      - media:/data
    depends_on:
      - db
      - redis

  # Corrected position for the scheduler service
  scheduler:
    build: .
    command: python -m scheduler.scheduler
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata: {}
  media: {}